// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6UsJJSKGf0oz4LGWVspYf_OmilL0zPoM',
    appId: '1:411016977572:web:903da1ab30e148bb931a31',
    messagingSenderId: '411016977572',
    projectId: 'finalapp-7253a',
    authDomain: 'finalapp-7253a.firebaseapp.com',
    storageBucket: 'finalapp-7253a.appspot.com',
    measurementId: 'G-GTL40H70XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkhHPi5hcIrKxUHwUygspwxuYggy4Fejs',
    appId: '1:411016977572:android:0113b95a1cf5aebb931a31',
    messagingSenderId: '411016977572',
    projectId: 'finalapp-7253a',
    storageBucket: 'finalapp-7253a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR_HC0jGs0DmshX4QquKVak41hExi7Vzg',
    appId: '1:411016977572:ios:069c095a47d940ae931a31',
    messagingSenderId: '411016977572',
    projectId: 'finalapp-7253a',
    storageBucket: 'finalapp-7253a.appspot.com',
    iosBundleId: 'com.example.graduateproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR_HC0jGs0DmshX4QquKVak41hExi7Vzg',
    appId: '1:411016977572:ios:28573fed2a8da957931a31',
    messagingSenderId: '411016977572',
    projectId: 'finalapp-7253a',
    storageBucket: 'finalapp-7253a.appspot.com',
    iosBundleId: 'com.example.graduateproject.RunnerTests',
  );
}
